import type { Metadata } from "next";
import "./globals.css";
import {Noto_Sans_Display} from "next/font/google"
import {ClerkProvider } from '@clerk/nextjs'

const noto = Noto_Sans_Display({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Dasboard Ventas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={noto.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
